hackmdPostgres:
  image: postgres
  environment:
    POSTGRES_USER: hackmd
    POSTGRES_PASSWORD: hackmdpass
    POSTGRES_DB: hackmd

hackmd:
  image: hackmdio/hackmd:0.4.5
  environment:
    POSTGRES_USER: hackmd
    POSTGRES_PASSWORD: hackmdpass
    NODE_ENV: "${NODE_ENV}"
    DEBUG: "${DEBUG}"
    HMD_DOMAIN: "${HMD_DOMAIN}"
    HMD_URL_PATH: "${HMD_URL_PATH}"
    HMD_PORT: "${HMD_PORT}"
    HMD_ALLOW_ORIGIN: "${HMD_ALLOW_ORIGIN}"
    HMD_PROTOCOL_USESSL: "${HMD_PROTOCOL_USESSL}"
    HMD_URL_ADDPORT: "${HMD_URL_ADDPORT}"
    HMD_USECDN: "${HMD_USECDN}"
    HMD_FACEBOOK_CLIENTID: "${HMD_FACEBOOK_CLIENTID}"
    HMD_FACEBOOK_CLIENTSECRET: "${HMD_FACEBOOK_CLIENTSECRET}"
    HMD_TWITTER_CONSUMERKEY: "${HMD_TWITTER_CONSUMERKEY}"
    HMD_TWITTER_CONSUMERSECRET: "${HMD_TWITTER_CONSUMERSECRET}"
    HMD_GITHUB_CLIENTID: "${HMD_GITHUB_CLIENTID}"
    HMD_GITHUB_CLIENTSECRET: "${HMD_GITHUB_CLIENTSECRET}"
    HMD_GITLAB_BASEURL: "${HMD_GITLAB_BASEURL}"
    HMD_GITLAB_CLIENTID: "${HMD_GITLAB_CLIENTID}"
    HMD_GITLAB_CLIENTSECRET: "${HMD_GITLAB_CLIENTSECRET}"
    HMD_DROPBOX_CLIENTID: "${HMD_DROPBOX_CLIENTID}"
    HMD_DROPBOX_CLIENTSECRET: "${HMD_DROPBOX_CLIENTSECRET}"
    HMD_GOOGLE_CLIENTID: "${HMD_GOOGLE_CLIENTID}"
    HMD_GOOGLE_CLIENTSECRET: "${HMD_GOOGLE_CLIENTSECRET}"
    HMD_IMGUR_CLIENTID: "${HMD_IMGUR_CLIENTID}"
    HMD_EMAIL: "${HMD_EMAIL}"
    HMD_IMAGE_UPLOAD_TYPE: "${HMD_IMAGE_UPLOAD_TYPE}"
    HMD_S3_ACCESS_KEY_ID: "${HMD_S3_ACCESS_KEY_ID}"
    HMD_S3_SECRET_ACCESS_KEY: "${HMD_S3_SECRET_ACCESS_KEY}"
    HMD_S3_REGION: "${HMD_S3_REGION}"
    HMD_S3_BUCKET: "${HMD_S3_BUCKET}"
  links:
    - hackmdPostgres
